tags: ['kythe_bazel_extract']
substitutions:
  _BAZEL_TARGET: '//...'
steps:
- id: 'clone'
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', '${REPO_NAME}', '.']
  dir: 'code/'
- id: 'checkout'
  name: 'gcr.io/cloud-builders/git'
  args: ['checkout', '${COMMIT_SHA}']
  dir: 'code/'
- id: 'extract'
  name: 'gcr.io/kythe-public/bazel-extractor'
  args: ['build', '-k', '--define', 'kythe_corpus=${_KYTHE_CORPUS}', '${_BAZEL_TARGET}']
  dir: 'code/'
- id: 'rename'
  name: 'ubuntu'
  args: ['mv', 'output/compilations.kzip', 'output/${COMMIT_SHA}.kzip']
artifacts:
  objects:
    location: 'gs://${_BUCKET_NAME}/${_KYTHE_CORPUS}/'
    paths: ['/workspace/output/${COMMIT_SHA}.kzip']
